version: "3"
services:
  front:
    build: .
    volumes:
      - .:/myapp
    environment:
      - VUE_APP_API_ENDPOINT=http://localhost
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    command: yarn serve
